language: python

python:
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coveralls

script:
  - coverage run --source=wikimapia_api setup.py test

after_success:
  - coveralls
