language: python

python:
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coveralls
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - pip install jinja2

script:
  - python -m unittest discover
